using Content.Shared.Clothing;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutContainer : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;

    private readonly EntityUid? _entity;

    public event Action<string?>? OnCustomNameChanged; // Claw Command

    public Button Select => SelectButton;
    public BoxContainer ItemRow => TopRow; // Claw Command - expose for toggle button placement

    public string? Text
    {
        get => SelectButton.Text;
        set => SelectButton.Text = value;
    }

    public LoadoutContainer(ProtoId<LoadoutPrototype> proto, bool disabled, FormattedMessage? reason)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SelectButton.Disabled = disabled;

        if (disabled && reason != null)
        {
            var tooltip = new Tooltip();
            tooltip.SetMessage(reason);
            SelectButton.TooltipSupplier = _ => tooltip;
        }

        // Claw Command - custom loadout item naming
        CustomNameEdit.IsValid = text => text.Length <= 15;
        CustomNameEdit.OnTextChanged += args =>
        {
            var name = args.Text.Trim();
            OnCustomNameChanged?.Invoke(name.Length >= 3 ? name : null);
        };

        if (_protoManager.Resolve(proto, out var loadProto))
        {
            var ent = loadProto.DummyEntity ?? _entManager.System<LoadoutSystem>().GetFirstOrNull(loadProto);

            if (ent == null)
                return;

            _entity = _entManager.SpawnEntity(ent, MapCoordinates.Nullspace);
            Sprite.SetEntity(_entity);

            var spriteTooltip = new Tooltip();
            spriteTooltip.SetMessage(FormattedMessage.FromUnformatted(_entManager.GetComponent<MetaDataComponent>(_entity.Value).EntityDescription));

            TooltipSupplier = _ => spriteTooltip;
        }
    }

    // Claw Command - custom loadout item naming
    public void SetCustomNameVisible(bool visible, string? currentName = null)
    {
        CustomNameEdit.Visible = visible;
        if (visible)
            CustomNameEdit.Text = currentName ?? string.Empty;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing)
            return;

        _entManager.DeleteEntity(_entity);
    }
}
