using Content.Shared._ClawCommand.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Linq;

namespace Content.Client._ClawCommand.Administration.UI.PlayTimeEditor;

[GenerateTypedNameReferences]
public sealed partial class PlayTimeEditorWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly SpriteSystem _spriteSystem;

    public Action<(string targetName, List<PlayTimeAdjustment> adjustments, bool overwrite)>? OnSubmit;
    private TimeSpan? _confirmResetAt { get; set; }

    public PlayTimeEditorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entityManager.System<SpriteSystem>();

        AddButton.OnButtonUp += OnAddPressed;
        OverwriteButton.OnButtonUp += OnOverwritePressed;
        BatchCheckbox.OnPressed += OnBatchToggled;

        RoleSearch.OnTextChanged += OnSearchChanged;

        LoadRoles();
        RefreshBatchMode();
        SetStatus(" ", Color.LightGreen);
    }

    public void LoadRoles()
    {
        var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>()
            .OrderBy(job => job.LocalizedName)
            .ToList();

        foreach (var job in jobs)
        {
            var entry = new PlayTimeEditorEntry(job, _spriteSystem, _prototypeManager);
            RoleContainer.AddChild(entry);
        }
    }

    public void UpdatePermissions(bool hasPermission)
    {
        AddButton.Visible = hasPermission;
        OverwriteButton.Visible = hasPermission;

        if (!hasPermission)
            SetStatus(Loc.GetString("playtime-editor-status-no-perms"), Color.DarkRed);
        else
            SetStatus(" ", Color.LightGreen);
    }

    public void ApplyChanges(bool overwrite = false)
    {
        var target = TargetInput.Text;

        if (string.IsNullOrEmpty(target))
        {
            SetStatus(Loc.GetString("playtime-editor-status-no-target"), Color.DarkRed);
            return;
        }

        var adjustments = new List<PlayTimeAdjustment>();

        if (BatchCheckbox.Pressed)
        {
            if (string.IsNullOrEmpty(BatchDurationInput.Text))
            {
                SetStatus(Loc.GetString("playtime-editor-status-batch-no-duration"), Color.DarkRed);
                return;
            }

            var selected = GetSelectedEntries();
            foreach (var entry in selected)
            {
                var item = new PlayTimeAdjustment(entry.RoleTracker, BatchDurationInput.Text);
                adjustments.Add(item);
            }
        }
        else
        {
            foreach (var child in RoleContainer.Children)
            {
                if (child is not PlayTimeEditorEntry entry)
                    continue;

                var tracker = entry.RoleTracker;
                var durationText = entry.GetDurationText();

                if (string.IsNullOrEmpty(durationText))
                    continue;

                var item = new PlayTimeAdjustment(tracker, durationText);
                adjustments.Add(item);
            }
        }

        OnSubmit?.Invoke((target, adjustments, overwrite));
        SetStatus(Loc.GetString("playtime-editor-status-processing"), Color.Gold);
    }

    public List<PlayTimeEditorEntry> GetSelectedEntries()
    {
        var list = new List<PlayTimeEditorEntry>();

        foreach (var child in RoleContainer.Children)
        {
            if (child is not PlayTimeEditorEntry entry)
                continue;

            if (entry.IsSelected())
                list.Add(entry);
        }

        return list;
    }

    public void RefreshBatchMode()
    {
        BatchDurationInput.Visible = BatchCheckbox.Pressed;

        foreach (var child in RoleContainer.Children)
        {
            if (child is not PlayTimeEditorEntry entry)
                continue;

            entry.SetGroupMode(BatchCheckbox.Pressed);
        }
    }

    public void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        FilterRoles();
    }

    public void FilterRoles()
    {
        foreach (var child in RoleContainer.Children)
        {
            if (child is not PlayTimeEditorEntry entry)
                continue;

            entry.Visible = MatchesSearch(entry);
        }
    }

    public void SetStatus(string text, Color color)
    {
        StatusLabel.FontColorOverride = color;
        StatusLabel.Text = text;
    }

    public bool MatchesSearch(PlayTimeEditorEntry entry)
    {
        return entry.RoleName != null && RoleSearch.Text != null && entry.RoleName.Contains(RoleSearch.Text, StringComparison.OrdinalIgnoreCase);
    }

    public void OnBatchToggled(BaseButton.ButtonEventArgs obj)
    {
        RefreshBatchMode();
    }

    public void OnAddPressed(BaseButton.ButtonEventArgs obj)
    {
        ApplyChanges(false);
    }

    public void OnOverwritePressed(BaseButton.ButtonEventArgs obj)
    {
        if (_confirmResetAt is null)
        {
            _confirmResetAt = _gameTiming.CurTime.Add(TimeSpan.FromSeconds(3));
            OverwriteButton.ModulateSelfOverride = Color.DarkRed;
            OverwriteButton.Text = Loc.GetString("playtime-editor-overwrite-confirm");
            return;
        }

        ApplyChanges(true);
        ResetOverwriteButton();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_confirmResetAt != null && _gameTiming.CurTime > _confirmResetAt)
            ResetOverwriteButton();
    }

    private void ResetOverwriteButton()
    {
        _confirmResetAt = null;
        OverwriteButton.ModulateSelfOverride = null;
        OverwriteButton.Text = Loc.GetString("playtime-editor-overwrite-time");
    }
}
