using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ClawCommand.Administration.UI.PlayTimeEditor;

[GenerateTypedNameReferences]
public sealed partial class PlayTimeEditorEntry : BoxContainer
{
    public string RoleTracker;
    public string RoleName;

    public PlayTimeEditorEntry(JobPrototype jobProto, SpriteSystem spriteSystem, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RoleTracker = jobProto.PlayTimeTracker;
        RoleLabel.Text = jobProto.LocalizedName;
        RoleName = jobProto.LocalizedName;

        if (prototypeManager.TryIndex<JobIconPrototype>(jobProto.Icon, out var jobIcon))
            RoleIcon.Texture = spriteSystem.Frame0(jobIcon.Icon);
    }

    public void SetGroupMode(bool grouped)
    {
        DurationLabel.Visible = !grouped;
        DurationInput.Visible = !grouped;
        SelectionCheckbox.Visible = grouped;
    }

    public string GetDurationText()
    {
        return DurationInput.Text != null ? DurationInput.Text : "";
    }

    public bool IsSelected()
    {
        return SelectionCheckbox.Pressed;
    }
}
