using System;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Content.Shared._ClawCommand.Devices.Components;

namespace Content.Client._ClawCommand.Entities.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class PinpointerCrewWindow : DefaultWindow
    {
        public int? SelectedCrew;
        public int? CurrentCrewId;
        public event Action? SelectCrewPressed;

        public PinpointerCrewWindow()
        {
            RobustXamlLoader.Load(this);

            SelectCrewButton.OnPressed += _ => SelectCrewPressed?.Invoke();
            CrewList.OnItemSelected += CrewListOnItemSelected;
            CrewList.OnItemDeselected += CrewListOnItemDeselected;
        }

        public void SetSelectedCrew(int? id, string name)
        {
            CurrentCrewId = id;
            CurrentCrewLabel.Text = Loc.GetString("comp-pinpointer-crew-select-current") + $" {name}";
            CrewList.ClearSelected();
        }

        public void PopulateCrewListUIXML(List<PinpointedCrew> crewData)
        {
            CrewList.Clear();

            foreach (var crew in crewData)
            {
                CrewList.Add(GetCrewItem(crew.ID, crew.Name, CrewList));
            }
        }

        private static ItemList.Item GetCrewItem(int id, string name, ItemList itemList)
        {
            return new(itemList)
            {
                Metadata = id,
                Text = name
            };
        }

        private void CrewListOnItemSelected(ItemList.ItemListSelectedEventArgs obj)
        {
            SelectedCrew = (int) obj.ItemList[obj.ItemIndex].Metadata!;
            if (SelectedCrew != CurrentCrewId) SelectCrewButton.Disabled = false;
        }

        private void CrewListOnItemDeselected(ItemList.ItemListDeselectedEventArgs obj)
        {
            SelectedCrew = CurrentCrewId;
        }
    }
}
