- type: job
  id: ClawCommandOfficer
  name: JobClawCommandOfficer
  description: job-description-cco
  playTimeTracker: JobClawCommandOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h
  startingGear: ClawCommandOfficerGear
  icon: "JobIconClawCommandOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Atmospherics
  - Medical
  - Research
  - Engineering
  - Command
  - CentralCommand
  - ClawCommand
  - Kitchen
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ClawCommandOfficerGear
  equipment:
    eyes: ClothingEyesGlassesMedSec
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58
    id: ClawCommandOfficerPDA
  storage:
    back:
    - Flash
    - MagazinePistol

- type: job
  id: ClawCommandMaid
  name: JobClawCommandMaid
  description: job-description-ccm
  playTimeTracker: JobClawCommandMaid
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h
  startingGear: ClawCommandMaidGear
  icon: "JobIconClawCommandMaid"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Service
  - Janitor
  - Medical
  - Command
  - CentralCommand
  - Bar
  - Kitchen
  - Hydroponics
  - Theatre
  - Cargo
  - Salvage
  - ClawCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ClawCommandMaidGear
  equipment:
    eyes: ClothingEyesGlassesMedSec
    ears: ClothingHeadsetAltCommand
    belt: WeaponMeleeKatana
    id: ClawCommandMaidPDA
  storage:
    back:
    - Flash


- type: chameleonOutfit
  id: ClawCommandOfficerChameleonOutfit
  job: ClawCommandOfficer
  hasMindShield: true
  equipment:
    eyes: ClothingEyesGlassesMedSec

- type: chameleonOutfit
  id: ClawCommandMaidChameleonOutfit
  job: ClawCommandMaid
  hasMindShield: true
  equipment:
    eyes: ClothingEyesGlassesMedSec
    hands: ClothingHandsGlovesCombat
