- type: job
  id: CentralCommandOfficial
  name: job-name-centcommoff
  description: job-description-centcommoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcommGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcommGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesHop
    outerClothing: ClothingOuterArmorCentcommCarapace
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    back: ClothingBackpackSatchelCentComm
    belt: ClothingBeltStorageWaistbag
    pocket1: WeaponPistolN1984
  storage:
    back:
      - BoxSurvivalMilitaryDouble
      - BoxFolderCentComClipboardThreePapers
      - MagazineMagnum
      - MagazineMagnum
      - RubberStampCentcom
      - PenCentcom

- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
